Rack Time Format v1.0
Savelov-Vitaliy/rack pull request #1
Opened 2018-10-24 07:36 UTC by Savelov-Vitaliy

2018-10-24 16:15 UTC, iBublik requested changes

2018-10-24 16:15 UTC, iBublik commented on app.rb
> +    query_string = env['QUERY_STRING'].split('=')[1]
Использование Rack::Request значиетльно упростит код

2018-10-24 16:15 UTC, iBublik commented on app.rb
> +      unknown_format = query_format.keys - AVAILABLE_FORMAT.keys
Логику форматирования стоит вынести в отдельный класс, который не знает, где он используется (никакой HTTP-специфики в нем быть не должно). Т.е. ты делаешь что-то типа 
```ruby
formatter = TimeFormatter.new(params)
if formatter.success?
  # отдаем успшный ответ
else
  # отдаем ошибку
end
```

2018-10-24 16:15 UTC, iBublik commented on app.rb
> +      if url != '/time'
Неверный url лучше сразу обработать, чтоб потом в коде меньше веток было

2018-10-25 06:28 UTC, iBublik requested changes

2018-10-25 06:28 UTC, iBublik commented on .byebug_history
> +c
Это надо убрать из репозитория

2018-10-25 06:28 UTC, iBublik commented on app.rb
> +  require_relative 'time_formatter'
Подключение файлов стоит в самом верху держать, до объявления класса

2018-10-25 06:28 UTC, iBublik commented on app.rb
> +        @body = [Time.now.strftime(formatter.get_formats)]
Это тоже ответственность TimeFormatter, а не твоего App-а. Он должен вернуть конечный результат `formatter.formatted_time`

2018-10-25 06:28 UTC, iBublik commented on middleware/url_filter.rb
> +  VALID_URL = '/time'
Не забывай freeze-ить мутабельные объекты в константах

2018-10-25 06:28 UTC, iBublik commented on app.rb
> +    unless request.params['format']
`unless` с `else` абсолютно нечитабелен, никогда так не пиши

2018-10-25 06:28 UTC, iBublik commented on middleware/url_filter.rb
> +
Коль уж создал отдельный миддлвар для фильтрации запросов, тут же стоит проверить, что в запросе есть все необходимые параметры (`format`)

2018-10-25 06:28 UTC, iBublik commented on time_formatter.rb
> +    params.map(&:to_sym).map {|k| @query_formats[k] = VALID_FORMATS[k]}
Для получения хеша из другой коллекции используй `each.with_object({})`

2018-10-25 09:33 UTC, Savelov-Vitaliy commented on middleware/url_filter.rb
> +  VALID_URL = '/time'
ОК. Но не понимаю зачем.

2018-10-25 09:38 UTC, Savelov-Vitaliy commented on time_formatter.rb
> +    params.map(&:to_sym).map {|k| @query_formats[k] = VALID_FORMATS[k]}
точно! 
не заякорилось в прошлый раз :))

2018-10-25 12:21 UTC, Savelov-Vitaliy commented on time_formatter.rb
> +    params.map(&:to_sym).map {|k| @query_formats[k] = VALID_FORMATS[k]}
@query_formats = params.split(',').map(&:to_sym).each.with_object({}) {|key, hash| hash[key] = VALID_FORMATS[key]}
Не уверен что лучше получилось. 
Или each.with_object({}) быстрее отрабатывает в сравнении с map ?

2018-10-25 15:27 UTC, iBublik commented on middleware/url_filter.rb
> +  VALID_URL = '/time'
Иначе это не константа - `VALID_URL << 'qwe'`

2018-10-25 15:35 UTC, iBublik approved these changes

2018-10-25 15:35 UTC, iBublik commented on middleware/filter.rb
> +    if !request.params['format']
Вот тут как раз уместен unless

2018-10-25 15:35 UTC, iBublik commented on middleware/filter.rb
> +  def body
`attr_reader :status, :body`

2018-10-25 15:35 UTC, iBublik commented on time_formatter.rb
> +    @query_formats = params.split(',').map(&:to_sym).each.with_object({}) {|key, hash| hash[key] = VALID_FORMATS[key]}
Это однозначно лучше, потому что код делает строго, что от него ожидаешь. Плюс ты не мутируешь какую-то внешнюю переменную, а работаешь с параметром блока. Это считается идиоматичным Ruby

2018-10-25 15:35 UTC, iBublik commented on time_formatter.rb
> +    VALID_FORMATS.keys.inspect
`inspect` тут лишний, это сужает круг решаемых методом задач

2018-10-25 17:25 UTC, Savelov-Vitaliy commented on time_formatter.rb
> +    @query_formats = params.split(',').map(&:to_sym).each.with_object({}) {|key, hash| hash[key] = VALID_FORMATS[key]}
ОК, это понятно.

2018-10-25 17:28 UTC, Savelov-Vitaliy commented on time_formatter.rb
> +    VALID_FORMATS.keys.inspect
точно. 
убрал и работает! :)

2018-10-25 17:29 UTC, Savelov-Vitaliy commented on middleware/filter.rb
> +  def body
в App так же сделаю

2018-10-25 17:32 UTC, merged